name: preCICE Matrix Notify Action
description: Send status of a GitHub workflow to a Matrix

inputs:
  homeserver:
    required: true

  login:
    required: true

  password:
    required: true

  room_id:
    required: true

  status:
    required: false
    default: ${{ job.status }}

  repository:
    required: false
    default: ${{ github.repository }}

  name:
    required: false
    default: ${{ github.workflow }}

  link:
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  tag_all:
    required: false
    default: "false"

runs:
  using: composite

  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ">=3.13"

    - name: Install dependencies
      shell: bash
      run: |
        cd "$GITHUB_ACTION_PATH"
        pip install -r requirements.txt

    - name: Send Matrix message
      shell: bash
      env:
        HOMESERVER: ${{ inputs.homeserver }}
        LOGIN: ${{ inputs.login }}
        PASSWORD: ${{ inputs.password }}
        ROOM_ID: ${{ inputs.room_id }}
        STATUS: ${{ inputs.status }}
        REPO: ${{ inputs.repository }}
        NAME: ${{ inputs.name }}
        LINK: ${{ inputs.link }}
        TAG_ALL: ${{ inputs.tag_all }}
      run: |
        cd "$GITHUB_ACTION_PATH"
        python ./notify.py
